import type { Plugin } from '../types';
export declare const boldPlugin: Plugin;
export declare const italicPlugin: Plugin;
export declare const underlinePlugin: Plugin;
export declare const strikePlugin: Plugin;
export declare const codePlugin: Plugin;
export declare const headingPlugin: Plugin;
export declare const listPlugin: Plugin;
export declare const blockquotePlugin: Plugin;
export declare const linkPlugin: Plugin;
export declare const alignmentPlugin: Plugin;
export declare const clearFormatPlugin: Plugin;
export declare const historyPlugin: Plugin;
export declare const defaultPlugins: Plugin[];
